version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 0
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    env_file: .env
    ports:
      - 8004:80
      - 9020:443
    volumes:
      # - ./:/var/www
      #  - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./default.conf:/etc/nginx/sites-enabled/default
    - ./ssl.crt:/etc/ssl/ssl.crt
    - ./ssl.key:/etc/ssl/ssl.key
      # - ./ssl.conf:/etc/nginx/sites-enabled/default
        #command: /bin/chown -R www-data:www-data /var/www/
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
